### ISSUE TITLE
BufSTFT: sampleRate of `resynth` buffer not being set "properly"

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-sc#100]
When using `inverse`=1 and passing a buffer to `resynth` the resulting sample rate of that buffer seems to be the sampleRate of the `magnitude` buffer * the `hopSize`, which makes sense when the sampleRate of the `magnitude` buffer is ~86 Hz because it is frames. 

However, if I pack my own buffer of magnitudes (as below) and then as to do resynthesis with this buffer the sample rate of the `resynth` buffer is 22579200 Hz. (This is 44100 * 512).

I tried setting the sampleRate of my "hand rolled" buffer to ~86, but this doesn't seem to have worked, maybe a lang vs. server thing. I even post the buffers to be sure that both `magnitude` and `phase` buffers have the appropriate sampleRate before doing the inverse STFT (~86 Hz), and it still is giving me a sample rate of 22579200 Hz).

(note that this doesn't happen if I pass the original `magnitude` buffer to the inverse STFT).

Code that reproduces:

```
s.boot;

~src = Buffer.read(s,FluidFilesPath("Olencki-TenTromboneLongTones-M.wav"));

~src.play;

// see the spectrogram of magnitudes
(
~mags = Buffer(s);
~phases = Buffer(s);
FluidBufSTFT.processBlocking(s,~src,magnitude:~mags,phase:~phases);
)

// transform the magnitudes in the frequency domain for the spectral adjustments
(
~mags.loadToFloatArray(action:{
	arg mags;
	fork{
		var new_mags = Buffer.alloc(s,~mags.numFrames,~mags.numChannels);
		
		s.sync;
		
		"mags: %".format(mags).postln;
		
		mags = mags.clump(~mags.numChannels);
		mags = mags.collect{
			arg frame, idx;
			"frame %:\t%".format(idx,frame).postln;
			frame.collect{
				arg mag, bin;
				mag = mag * bin.linlin(0,frame.size-1,0,pi/2).sin.abs;
			};
		};
		
		new_mags.loadCollection(mags.flat,action:{
			fork{
				// new_mags.sampleRate_(~mags.sampleRate);
				
				// s.sync;
				
				~resynth = Buffer(s);
				
				"magnitude: %".format(new_mags).postln;
				"phase:     %".format(~phases).postln;
				FluidBufSTFT.processBlocking(s,~src,magnitude:new_mags,phase:~phases,resynth:~resynth,inverse:1,action:{
					
					"playing resynth".postln;
					~resynth.postln;
					defer{FluidWaveform(~resynth)};
					~resynth.play;
					
				});
			}
			
		});
		
	}
});
)
```

**Comment by weefuzzy** [comment]
For some reason, your sample rate change isn't updating the actual buffer on the server

<img width="618" alt="Screenshot 2022-05-11 at 18 10 16" src="https://user-images.githubusercontent.com/27292769/167907744-bec17633-82e8-4d29-b223-d873ca4bec32.png">
