### ISSUE TITLE
exception in GraphDef_Recv: UGen 'FluidStandardizeQuery' not installed.

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-sc#105]
This is on 
flucoma-sc: 2e255cb9c5aa07d72defb5b03074cab2b2823e99
flucoma-core-src: e0264d77811c4e2a545711245716b34cc45a4c07

Code such as this recreates it:

```
// ~ds = an existing dataset

(
~ds_stand = FluidDataSet(s);
~stand = FluidStandardize(s).fitTransform(~ds,~ds_stand);
~tree = FluidKDTree(s).fit(~ds_stand);
)

(
{
	var sig = PlayBuf.ar(1,~test_buffer,BufRateScale.ir(~test_buffer),loop:1);
	var spec = FluidSpectralShape.kr(sig);
	var trig = Impulse.kr(10);
	var specbuf = LocalBuf(7);
	var standbuf = LocalBuf(7);
	var posbuf = LocalBuf(4);
	var posinfo;

	FluidKrToBuf.kr(spec,specbuf);
	~stand.kr(trig,specbuf,standbuf);

}.play;
)
```

**Comment by weefuzzy** [comment]
No problem here, so it's probably an installation problem – is this your own build or a downloaded one?

**Comment by tedmoore** [comment]
hmm. my own. i'll download the nightly and see.

**Comment by tedmoore** [comment]
yup nightly seems fine. Any inklings of how i may have built wrong?

**Comment by tedmoore** [comment]
Wait, it's back.

`exception in GraphDef_Recv: UGen 'FluidMLPRegressorQuery' not installed.`

Version:
`Fluid Corpus Manipulation Toolkit: version 1.0.0-TB2.beta6+sha.2e255cb.core.sha.e0264d7`

**Comment by tedmoore** [comment]
I think it only happens when I try to call .kr on a FluidDataObject. Then it says `Fluid(whatever data object)Query not installed`

**Comment by weefuzzy** [comment]
So, did it work for a bit, or not at all? Or ok in the nightly but not in your build? I'm confused now. Weird that it find the data plugin but not the corresponding query plugin because they live in the same binary. 

Oh...oh, hang on. (Goes at looks at the git status of the sc repo). 

Um. Forgot to commit something quite important. Sorry...

**Comment by weefuzzy** [comment]
commit b896744357db425d0b270d2b184e0528622e69f1 should fix this
