### ISSUE TITLE
BufNMF: add example where `basesMode` = 2 and `actMode` = 2

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-sc#106]
Add an example to the example code that does decomposition with `actMode` set to 2 and also `basesMode` set to 2. This will require pre-computed bases and activations to be supplied.

This is an added functionality since the example code was initially made.

**Comment by weefuzzy** [comment]
Doesn't necessarily need something pre computed. You could do a decomposition, then process the results in some way before re-synthesis, e.g. smoothing the activations.

**Comment by tremblap** [comment]
yes - I think that I'll do that in the learn ticket. so only the vocoder is missing from the help

**Comment by tremblap** [comment]
> Smoothing activations is a good one.

that was my plan :) with assymetric smoothing, like gerard and i experimented with 4 years ago. it should be fun, but deffo advanced so I plan to put that in learn, as per https://github.com/flucoma/learn-website/issues/324
