### ISSUE TITLE
cmake install routine messes-up the helpfiles

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-sc#107]
This picture shows, that post install, the folder created has both the old (wrong) helpfiles in the right folder (Classes) and an extra folder (sc_ref) with the right helpfiles in them...

<img width="813" alt="Screenshot 2022-05-31 at 13 53 26" src="https://user-images.githubusercontent.com/10000381/171179304-92ca9d10-f3f2-4728-87ff-87756627ae93.png">

I did all my pr reviews on the wrong ones because of this :( I'm sad.

**Comment by weefuzzy** [comment]
There will be a missing slash in the `install` command (or vice versa, never remember). Although this also raises a question for @tedmoore  about when we're going to zap old help files.

**Comment by jamesb93** [comment]
Line 264

**Comment by tremblap** [comment]
I'll let @tedmoore decide when/how best to move.

**Comment by tremblap** [comment]
in the meantime since it messes up the CI too I'll push the line change after testing it if @weefuzzy agrees

**Comment by tedmoore** [comment]
What would be lost by zapping the old help files? What is being zapped? Aren't we already building all the SC help from `flucoma-docs`?
