### ISSUE TITLE
FluidDataSet `.print` and `.free` ordering

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-sc#121]
I observed some behaviour today that went against my intuition so I'm curious to hear what @weefuzzy makes of it. I noticed that this prints the dataset:
```
(
fork{
	var point = Buffer.alloc(s,1);
	var ds = FluidDataSet(s);
	s.sync;
	10.do{
		arg i;
		point.set(0,i);
		ds.addPoint("point-%".format(i),point);
		s.sync;
	};
	ds.print;
};
)
```
but this does not
```
(
fork{
	var point = Buffer.alloc(s,1);
	var ds = FluidDataSet(s);
	s.sync;
	10.do{
		arg i;
		point.set(0,i);
		ds.addPoint("point-%".format(i),point);
		s.sync;
	};
	ds.print;
	ds.free;
};
)
```
So it seems what is happening is the DataSet is getting freed before it can print (in this case the `.print` to nothing isn't showing me an error though). In my heart what I *want* to happen is for the print and free to be lined up on the OSC cue one after the other so the `.free` can't be executed until after the print takes place. Why is this not the case?

**Comment by weefuzzy** [comment]
Hmm. My guess would be that, server side `free` is able to do its shizzle on the command FIFO thread straight away, whereas dispatching the result of a message like print has to wait for an additional round of exchange between RT and NRT threads (if you remember the weird four-step thing that all NRT commands go through). Presumably if `free` were always deferred to this later stage, then it would remain correctly ordered

**Comment by weefuzzy** [comment]
But actually, irrespective of that, you still want to wait until `print` has cleared the server before calling free, because it's still asynchronous and presumably(?) `free` entails making the object available for GC language side? 

What do you get with 
```js
ds.print;
s.sync; 
ds.free;
``

**Comment by weefuzzy** [comment]
Yes, now that's clear enough to me: because `free` has language-side effects as well, and is getting called immediately, then the issue isn't to do with the OSC queue ordering so much as that the instance will have been garbage collected in the language by the time `print` calls back, and so its OSC handler is no longer active. 

In short: use a `sync`, or a custom action.

**Comment by tedmoore** [comment]
> the instance will have been garbage collected in the language by the time `print` calls back, and so its OSC handler is no longer active.

Ah yes, and this is also why there's no error.

> If you wanted to experiment with this then it _might_ be as simple as changing `include/wrapper/NonRealtime.hpp` line 333 to say `stage4` rather than `stage2`.

So this suggestion is no longer applicable?
