### ISSUE TITLE
relationship between using `Buffer.set` and `FluidDataSet.addPoint`

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-sc#122]
Why do I need the `s.sync` after `.addPoint` here? Aren't all of these operations synchronous?

```
(
fork{
	var point = Buffer.alloc(s,1);
	var ds = FluidDataSet(s);
	s.sync;
	10.do{
		arg i;
		point.set(0,i);
		ds.addPoint("point-%".format(i),point);
		s.sync;
	};
	ds.print;
};
)
```

**Comment by weefuzzy** [comment]
*IIRC* it's because `Buffer` 'cheats' in way that we can't, and is able to execute its write immediately, on the RT thread, but in order for us to accurately track its state at each write, we need the sync to ensure that the `addPoint` is enqueued before the next `set` executes
