### ISSUE TITLE
FluidLoudness return

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-sc#15]
Ciao,

The FluidLoudness helpfile says that it returns:

_**A 2-channel KR signal with the [pitch, confidence] descriptors. The latency is windowSize.**_

which seems to be a copy paste error from FluidPitch.

Thanks!

T

**Comment by tremblap** [comment]
already correcte

**Comment by tremblap** [comment]
This was already corrected in the tip of the branch but indeed was wrong in the last public release :)
