### ISSUE TITLE
duplicate link in help file

### ISSUE THREAD

**Issue by paum3** [flucoma/flucoma-sc#161]
Hi I was not investigating this further, but accidentally I've found in FluidBufFlatten there are two links which point to the same url:
To learn more visit https://learn.flucoma.org/reference/bufflatten/.

Read more about FluidBufFlatten on the [learn platform](https://learn.flucoma.org/reference/bufflatten).

**Comment by tremblap** [comment]
fixed in [flucoma-docs ](https://github.com/flucoma/flucoma-docs) (where the source lives) commit 4b2317c
