### ISSUE TITLE
FluidKMeans returns strings

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-sc#19]
Greetings,

When I...

1. use ```fitPredict``` on FluidKMeans,
2. dump the FluidLabelSet that it puts the predictions in, and then
3. look into that Dictionary that it dumps, the cluster id integers are strings, as in...

```dict.at("data").at(key).class``` returns String

This was unexpected to me as they are integers.

Thanks!

**Comment by weefuzzy** [comment]
A `LabelSet` is a associative array of string IDs to string Labels, so even though KMeans is inventing the cluster labels as integers, they get stringified. (Remember C++ is statically typed, unlike SC) 

Admittedly, this makes more sense in the case of the classifiers (where the labels are the string IDs from the output training data). We can perhaps give some future thought to how to provide a simpler interface layer without sacrificing the flexibility of what we have.
