### ISSUE TITLE
flucoma-sc is available on the Arch User Repository

### ISSUE THREAD

**Issue by madskjeldgaard** [flucoma/flucoma-sc#3]
Hi, this is an FYI relevant for users on Arch Linux, but this project has been packaged for the AUR and can now be installed via the Arch User Repository:
`yay -S supercollider-flucoma`

More info here: https://aur.archlinux.org/packages/supercollider-flucoma/

**Comment by weefuzzy** [comment]
Amazing, thanks @madskjeldgaard. I'll update the README!
