### ISSUE TITLE
FluidMLPRegressor can't be saved with out training first

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-sc#31]
This makes sense since it doesn't know the shape of its input and output layers until training begins.

I think this should be made explicit in the documentation, or even better have it throw an error saying that it needs to be trained first. Right now, `.write` doesn't throw any error and a file is written to disk, but it only contains the word `null`.

**Comment by tedmoore** [comment]
I've added this to the milestone beta5, but only as a note to make sure it is in the documentation.

**Comment by tedmoore** [comment]
OK, so maybe this is a little more complicated to do. It seems that many of the objects that this applies to take their `.write` and `.dump` method language from the `defaults` document, however that document also provides the language for these methods to FluidDataSet and FluidLabelSet. Of course it doesn't make sense for their `.write` and `.dump` methods to also contain language about `This object must first be fit before dump can be called.`

I noticed that if the YAML contains an argument that is also in the `default` doc, the language in the YAML will be used (which I supposed is why the `default` doc is called default).

So I could default to this kind of language ("This object must first be fit before dump can be called.") for everything else and then override the defaults in FluidDataSet and FluidLabelSet YAMLs to not say that?

Unfortunately there is some CCE specific language in some of these defaults ("Dump the state of this object from the dump outlet") that would be lost, but perhaps this is an ok trade off?

Other ideas @weefuzzy?

**Comment by weefuzzy** [comment]
That sounds broadly on point. The sequence of fallbacks goes `YAML -> CCE specific defaults -> global defaults`, so where you need / want to have CCE specific phrasing, you can add an entry to the `defaults.py` for that CCE, and where it doesn't matter you can use the global one...

**Comment by tedmoore** [comment]
Got it. I will use that sequence to figure out what goes where!

**Comment by tedmoore** [comment]
this can be close upon merging https://github.com/flucoma/flucoma-docs/pull/57
