### ISSUE TITLE
FluidKDTree kNearest returns Symbol

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-sc#34]
When I `fit` the FluidKDTree, my FluidDataSet identifiers were all strings, so I expected the FluidKDTree to also return strings when I call `kNearest`. However it returns a Symbol.  I want to take the nearest it returns and compare it to my set of identifiers, but `==` won't work because they're different classes.

Can we make FluidKDTree return  the same class that was used to set the points in the FluidDataSet that it was trained on?

**Comment by weefuzzy** [comment]
I don't think this is something we have a great deal of control over: the encoding to `Symbol` takes place when SC itself parses the OSC packet. 

> FluidDataSet identifiers were all strings,

Not really: you may have put strings in, but these are converted to `Symbol`s, then serialized, sent over UDP and live on the server. This is what happens in `addPoint`
```supercollider
  addPointMsg{|identifier,buffer|
        buffer = this.prEncodeBuffer(buffer);
        ^this.prMakeMsg(\addPoint,id,identifier.asSymbol,buffer);
    }
```

We could, I guess, convert *everything* back to `String` across the toolkit, but is the loss in efficiency justified? `Symbol` is much cheaper to compare, and presumably there's some overhead in making lots of new `String`s?

**Comment by tedmoore** [comment]
I see. This makes sense. I will just make a note to clarify this in the docs.
