### ISSUE TITLE
boost dependencies not being pulled?

### ISSUE THREAD

**Issue by jamesb93** [flucoma/flucoma-sc#4]
Hello,

My steps to compile this for my machine (ARM m1) go as follows:

1. clone this repo
2. recurse clone supercollider
3. `mkdir -p build && cd build`
4. `cmake -DSC_PATH=../supercollider/ -DFLUID_ARCH=-mcpu=native ..`
5. `make install`

Which produces this error. 

`/Users/james/dev/software/flucoma-sc/include/SCBufferAdaptor.hpp:13:10: fatal error: 'boost/align/aligned_alloc.hpp' file not found`

I have boost installed on my system with `brew` so not too sure how to remedy this situation.

**Comment by jamesb93** [comment]
Needed to be cmake -DSC_PATH=../../supercollider/ -DFLUID_ARCH=-mcpu=native ..

**Comment by weefuzzy** [comment]
Phew! Glad you sorted it
