### ISSUE TITLE
Supercollider quits when using most (but not all) classes 

### ISSUE THREAD

**Issue by JordanHendersonMusic** [flucoma/flucoma-sc#45]
Short:
When running `FluidDataSet(s);` the server disconnects with this error
```
-> FluidDataSet(0)
Server 'localhost' exited with exit code 0.
server 'localhost' disconnected shared memory interface
```
However running the examples in the documentation for FluidAudioTransport everything works fine. 

OS: linux manjaro - ryzen 5600X
supercollider version: `scsynth -v`  3.12.1 (Built from branch 'not_a_git_checkout' [na])
present when installing through the following methods: download and drop in ~/.local/share/Supercollider/Exentsion, building from source, and installing for the AUR.
output of `FluidDataSet.version`: Fluid Corpus Manipulation Toolkit: version 1.0.0-TB2.beta4
I've also recompiled the class library.

Hi, 
I have an issue when using certain crucial classes, I  was going to ask over [here](https://discourse.flucoma.org/c/bug-reports-and-issues/5) but the account needs manually approving before I can post, but not here! Basically I can browse the documentation and use the Transform Audio UGens, but nothing else without the server disconnecting requiring me to kill it before I can reboot it. I was trying to get more information about the crash but I can't find any, so if you have any suggestion let me know!

Best,
Jordan

**Comment by weefuzzy** [comment]
Hiya, 

Thanks for the report. This sounds like it might be the same problem that came up in #26. The tl;dr is that when using SC built on Arch (and, thus preusmably Manjaro), one needs to make sure to build the FluCoMa tools using the same Boost as SC (which, on Arch at least, was the system one). Is your SC installation installed / built from AUR as well?

**Comment by JordanHendersonMusic** [comment]
Thank you for both the fast response and easy solution!

So you were right, the problem was boost. I was running the supercollider version from the manjaro package manager, which may or may not be the same as the AUR. I just built both supercollder and FluCoMa from source setting system boost on. I was hoping to avoid doing that but oh well! Seems like a supercollider problem.

Anyway, if any one else stumbles across this...
download and build supercollider and FluCoMa from source adding `-DSYSTEM_BOOST=ON` to the cmake flags each time. 

Cheers!

**Comment by heretogo** [comment]
@JordanHendersonMusic : do you use `-DSYSTEM_BOOST=ON` on both FluCoMa and SuperCollider builds? I am using Fedora and having the same issue.
