### ISSUE TITLE
macOS notarization

### ISSUE THREAD

**Issue by jarmitage** [flucoma/flucoma-sc#47]
<img width="532" alt="Screenshot 2022-01-07 at 15 21 01" src="https://user-images.githubusercontent.com/2885827/148565280-fe135f2d-eb89-4808-8746-650655e041b3.png">

**Comment by tedmoore** [comment]
Hi @jarmitage,

Take a look at step 3 on this page: https://learn.flucoma.org/installation/sc
Let me know if you're still having problems!

Cheers,

Ted

**Comment by jarmitage** [comment]
Ok, I see.

It would be handy if the installation instructions could be linked from this repo's README.

**Comment by jamesb93** [comment]
Good call, we'll make something that better points towards this in our docs. Thanks for raising an issue.

**Comment by tedmoore** [comment]
Fixed in https://github.com/flucoma/flucoma-sc/pull/54
