### ISSUE TITLE
FluidWaveform Interface & Raster Buffer Scaling

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-sc#50]
Greetings,

The interface is inconsistent between the Max and SC FluidWaveform objects. Should we resolve this by making them consistent across CCEs? The different argument names are:

(Max vs. SC)
* buffer vs. audioBuffer (audio that should be displayed as a waveform)
* image vs. rasterBuffer (for plotting a raster of spectrogram-type data, or MFCCs or Chroma)
* layer vs. featureBuffer (for plotting a squiggly line of other time-based data, like pitch)
* markers vs. indicesBuffer (for plotting vertical lines at particular indices)

Also I'm realizing that just passing in a buffer to create as a raster might cause some problems with scaling. For example, just linearly scaling STFT magnitudes to between 0 and 255 (for color lookup) doesn't make for a pretty or informative raster (see below).

So perhaps we need a way to let the user specify what type of scaling to use when creating the raster?

<img width="1323" alt="Screen Shot 2022-01-19 at 13 18 45" src="https://user-images.githubusercontent.com/1531144/150190460-cc85e5d7-7404-4398-8f4e-5a2ee60d5178.png">

**Comment by tremblap** [comment]
I prefer most of SC ames, except rasterBuffer - we need a better one for that.

and indeed we need scaling - although we have bufscale to do that, but I don't know how Max is handling that at the moment.

**Comment by tedmoore** [comment]
> except rasterBuffer - we need a better one for that

"imageBuffer"?

I think that FluidBufScale only does linear scaling (like `.linlin` in SC). The above image is linear scaling of magnitudes (`mags.linlin(0.0,mags.maxItem,0.0,255.0).asInteger` or something like that, as my "colors" array is 256 indices.) I think the thing we need is to be able to flag log scaling.

**Comment by tremblap** [comment]
the idea of linlog loglin and loglog for bufscale has been raised a few years ago, and even coded by yours truly. @weefuzzy are you still averse for it to happen? if so, we could do the log scale in the drawing process.

**Comment by weefuzzy** [comment]
In `fluid.waveform` the scaling is inherited from `fav.js`. Given a  magnitudes buffer, the data is scaled using 

```js
 desc.offset(1e-6).log().normalize();   
```

I'm not into the idea of there needing to be added C++ infrastructure (and thus maintenance burden) just to facilitate these utilities when the scaling could be done as part of drawing.

**Comment by tedmoore** [comment]
I'm happy to make it happen as part of drawing. The user will have to pass in which scaling to use. Is the FluCoMa pattern to copy the `FluidMLP*.sigmoid` pattern?:

FluidWaveform.lin = 0
FluidWaveform.log = 1

or just a 0 or 1?

**Comment by tremblap** [comment]
they are not exclusive so we can implement both and let users decide if they go for readability or tersness?
