### ISSUE TITLE
FluidKrToBuf: base on size of kr stream?

### ISSUE THREAD

**Issue by LFSaw** [flucoma/flucoma-sc#51]
I'd like to write a SynthDef collecting features of an audio stream in a buffer:

```sc
SynthDef(\rtAnalysis, {|out = 0, buf = 0, featureBuf = 1|
	var sig, mfccs, isPlaying;
	
	sig = PlayBuf.ar(1, buf, doneAction: 2);
	
	mfccs = FluidMFCC.kr(
		sig, q.numFccCoefs, 
		startCoeff: 1, 
		maxNumCoeffs: q.numFccCoefs
	); 

	FluidKrToBuf.kr(mfccs, featureBuf);
	
	sig!2

}).add;
```

my (naive) approach was to provide a buffer number here but soon i found out that a `Buffer` object is required:

https://github.com/flucoma/flucoma-sc/blob/e5c75cf3bb636a41a4b69fef03d34ba88833b6b2/release-packaging/Classes/FluidBufToKr.sc#L6

this implementation leads to 

```txt
^^ ERROR: Message 'numFrames' not understood.
RECEIVER: an OutputProxy
```

I'd propose to base the iteration in `FluidKrToBuf` on the dimensionality of the `kr` signal instead:

```sc
FluidKrToBuf {
	*kr {
		arg krStream, buffer;
		^krStream.collect{
			arg sig, i;
			BufWr.kr(sig, buffer, i);
		}
	}
}
```

A definition for `FluidBufToKr` is a little more involved but I could imagine that providing (optional) `numFrame` and `startFrame` arguments  would increase usability:

```sc
FluidBufToKr {
	*kr {
		arg buffer, numFrames, startFrame=0;


		if(buffer.isKindOf(Buffer), {
			numFrames = numFrames ?? {buffer.numFrames - startFrame};
		}, {
			numFrames = numFrames ? 1;
		});

		if(numFrames > 1,{
			^numFrames.collect{
				arg i;
				BufRd.kr(1,buffer,i,0,0);
			}
		},{
			^BufRd.kr(1,buffer,0,0,0);
		});
	}
}
```

After implementing this, I realised you already [fixed this in the dev branch](https://github.com/flucoma/flucoma-sc/blob/dev/release-packaging/Classes/FluidBufToKr.sc):

https://github.com/flucoma/flucoma-sc/blob/4e91cc363ef1f91a1a91aeb881000068aeafee4f/release-packaging/Classes/FluidBufToKr.sc#L19-L29

However, I could imagine that my `startFrame` argument might be a good addition ;)
Also, I'd recommend initialising numFrames with `nil` instead of `-1`.

Good work, anyhow!

**Comment by LFSaw** [comment]
I added a PR, feel free to include it :)

**Comment by tedmoore** [comment]
Thanks @LFSaw ! Yes, this is coming. I like your `startFrame` suggestion. I'll take a look at adding it to the dev branch code that exists!

Many of the FluCoMa objects use a `numFrames` default of -1 to indicate to use the rest of the buffer so here we're using -1 to be consistent across the toolkit.

Thank you!

Ted
