### ISSUE TITLE
FluidLabelSet has no `.setLabel` method in the sclang class definition

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-sc#56]
But the docs seem to think that it should, so I'm guessing that the C++ would like to be able to receive this kind of message, but there's currently no way to send it from sclang.

**Comment by tremblap** [comment]
I thought I did an old bug - this kind of bug I usually check in the core - actually I always check all bugs in another CCE to see if I put it in core (if common) as I was slapped on the fingers for not doing so in the past :)

**Comment by tremblap** [comment]
It is in the bitbucket list but not in github... I'll need to go there one day and port over the important ones...

**Comment by tedmoore** [comment]
I did check in Max, it has a setlabel message. I did the same with the padding issue as well just to make sure it was also an exposed argument elsewhere (I realise the ordering isn't a concern in Max though).

**Comment by tremblap** [comment]
oh la la sorry that came more forceful than intended. that'll teach me to write stuff quickly between meetings. if you see it in the c++ (and therefore in max) then it is an omission from the class def, and my fault. sorry!
