### ISSUE TITLE
problematic release-packaging/Resources folder

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-sc#59]
Hello

So we should ignore that Resource folder like we used to do for AudioFiles and Plugins - this is to allow us to work on a live version with the files in there but not actually being copied during install...

now it is quite potentially fraught with duplication.

proposals:

we manually put Resources/AudioFiles and Resources/Data in the .gitignore and we check that we remove them from the cmake (which at the moment copies the full content of the folder)

or

we move the CCE-unique resource in another folder at the top (sc-resources) and we git ignore the full of resources and copy sc-resource in resources at the same time we copy audiofiles and data.

I think I prefer the 2nd option.

**Comment by weefuzzy** [comment]
What's the problem? I'm not seeing it

**Comment by weefuzzy** [comment]
Oh, you mean the top-level resources folder getting committed by mistake. Yes, it should go into `.gitignore`. Bit trickier for Max, because there's stuff that's meant to live there and be tracked. Maybe we can make symlinks instead

**Comment by tremblap** [comment]
yeah, when we work on the local copy we need the Audio and Data to be in the packaging folder's Resources folder.

I think it would probably be cleaner to move the SC-only resources out of release-packaging/Resources and then put that full folder in .gitignore. The SC-only resources could be elsewhere and copied at package making.

(I've just re-worded my 2nd proposal above, just trying to make it clear)

I'm happy to do either and I'll do it quickly - I also need to change all the UTs who all bail (they don't know where the sounds are anymore :) but the toy datasets will be helpful for tests.
