### ISSUE TITLE
Linux: FreeSelfWhenDone does not free the monitoring synth in the examples.

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-sc#7]
Situation: In both Mac and Win, it works as expected, but on Linux, its use does not free the synth that is waiting to free itself in KR mode. It is true for all instances.

How to reproduce: trying the FluidBufThreadDemo KR example in the helpfile shows right away the avalanche of errors we get in that context.

**Comment by weefuzzy** [comment]
Did the PR in #11 make any difference to this issue?

**Comment by tremblap** [comment]
Well, it is sorted indeed! What is the magic at play?

**Comment by weefuzzy** [comment]
There was a logical error with setting the `done` status in the UGen when the NRT object couldn't be found in the cache.
