### ISSUE TITLE
bufmfcc creates the wrong number of channels

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-sc#96]
I investigated the first example of the helpfile after all UTs using MFCC failed.

1- bufmelbands works (I thought the new interface of MaxCoeff was the culprit)
2- the rt version of MFCC work
3- the order of parameters match the order of the 'client' in core

so I reckon it has to do with the new maxRegime and that this class def has a bug but I can't find it.

**Comment by tremblap** [comment]
to reproduce:

```
// load a sound
~buf = Buffer.read(s,FluidFilesPath("Harker-DS-TenOboeMultiphonics-M.wav"));

// do a FluidBufMFCC analysis
(
~mfccs = Buffer(s);
FluidBufMFCC.processBlocking(s,~buf,features:~mfccs,action:{"done".postln;})
)

// expecting 13 getting 2 channels
~mfccs.query
```

**Comment by weefuzzy** [comment]
Hum. Actually, in debug , it crashes. Looks like the SC class definition update never made it upstream 😢

**Comment by weefuzzy** [comment]
try with the commit above

**Comment by tremblap** [comment]
fixed indeed thanks

**Comment by tremblap** [comment]
I'm curious though: the melband method signature looked incredibly similar. I'll read them carefully

**Comment by weefuzzy** [comment]
just do a diff. it’s what gets sent to the server that matters in this case
